// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
//
// The division rows only (slug, labels, Lucide icon name, brand color, real
// agent count), so the landing page can render its category grid and hero
// shortcuts without shipping the full catalog. Run: bun run catalog
import type { CatalogDivision } from "./catalog.generated";

export const divisions: CatalogDivision[] = [
  {
    "slug": "academic",
    "label": "Academic",
    "labelFa": "دانشگاهی",
    "icon": "GraduationCap",
    "color": "#8B5CF6",
    "count": 6
  },
  {
    "slug": "design",
    "label": "Design",
    "labelFa": "طراحی",
    "icon": "PenTool",
    "color": "#EC4899",
    "count": 10
  },
  {
    "slug": "engineering",
    "label": "Engineering",
    "labelFa": "مهندسی",
    "icon": "Code",
    "color": "#3B82F6",
    "count": 64
  },
  {
    "slug": "finance",
    "label": "Finance",
    "labelFa": "مالی",
    "icon": "DollarSign",
    "color": "#22C55E",
    "count": 5
  },
  {
    "slug": "game-development",
    "label": "Game Development",
    "labelFa": "بازی‌سازی",
    "icon": "Gamepad2",
    "color": "#A855F7",
    "count": 6
  },
  {
    "slug": "gis",
    "label": "GIS",
    "labelFa": "سیستم اطلاعات جغرافیایی",
    "icon": "Map",
    "color": "#14B8A6",
    "count": 13
  },
  {
    "slug": "healthcare",
    "label": "Healthcare",
    "labelFa": "سلامت",
    "icon": "Stethoscope",
    "color": "#0D9488",
    "count": 3
  },
  {
    "slug": "marketing",
    "label": "Marketing",
    "labelFa": "مارکتینگ",
    "icon": "Megaphone",
    "color": "#F97316",
    "count": 36
  },
  {
    "slug": "paid-media",
    "label": "Paid Media",
    "labelFa": "رسانه پرداختی",
    "icon": "Target",
    "color": "#EAB308",
    "count": 7
  },
  {
    "slug": "product",
    "label": "Product",
    "labelFa": "محصول",
    "icon": "Box",
    "color": "#D946EF",
    "count": 5
  },
  {
    "slug": "project-management",
    "label": "Project Management",
    "labelFa": "مدیریت پروژه",
    "icon": "ClipboardList",
    "color": "#0EA5E9",
    "count": 7
  },
  {
    "slug": "research",
    "label": "Research",
    "labelFa": "پژوهش",
    "icon": "Search",
    "color": "#7C3AED",
    "count": 1
  },
  {
    "slug": "sales",
    "label": "Sales",
    "labelFa": "فروش",
    "icon": "TrendingUp",
    "color": "#10B981",
    "count": 9
  },
  {
    "slug": "security",
    "label": "Security",
    "labelFa": "امنیت",
    "icon": "ShieldCheck",
    "color": "#EF4444",
    "count": 12
  },
  {
    "slug": "spatial-computing",
    "label": "Spatial Computing",
    "labelFa": "رایانش فضایی",
    "icon": "Boxes",
    "color": "#06B6D4",
    "count": 6
  },
  {
    "slug": "specialized",
    "label": "Specialized",
    "labelFa": "تخصصی",
    "icon": "Sparkles",
    "color": "#6366F1",
    "count": 59
  },
  {
    "slug": "support",
    "label": "Support",
    "labelFa": "پشتیبانی",
    "icon": "LifeBuoy",
    "color": "#84CC16",
    "count": 6
  },
  {
    "slug": "testing",
    "label": "Testing",
    "labelFa": "تست",
    "icon": "FlaskConical",
    "color": "#F59E0B",
    "count": 9
  }
];
