// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
//
// The featured agents only, so the landing page does not ship the full catalog.
// Run: bun run catalog
import type { CatalogAgent } from "./catalog.generated";

export const featuredAgents: CatalogAgent[] = [
  {
    "id": "design-image-prompt-engineer",
    "slug": "design-image-prompt-engineer",
    "icon": "📷",
    "name": "Image Prompt Engineer",
    "category": "طراحی",
    "division": "design",
    "divisionLabel": "Design",
    "price": 39000,
    "rating": 4.9,
    "sales": 819,
    "description": "Expert photography prompt engineer specializing in crafting detailed, evocative prompts for AI image generation. Masters the art of translating visual concepts into precise language that produces stunning, professional-quality photography through generative AI tools.",
    "longDescription": "Translates visual concepts into precise prompts that produce stunning AI photography.",
    "features": [
      "Expert photography prompt engineer specializing in crafting detailed, evocative prompts for AI image generation. Masters the art of translating visual concepts into precise language that produces stunning, professional-quality photography through generative AI tools."
    ],
    "prompts": [
      "Craft detailed, structured prompts that produce professional-quality AI-generated photography",
      "Translate abstract visual concepts into precise, actionable prompt language",
      "Optimize prompts for specific AI platforms (Midjourney, DALL-E, Stable Diffusion, Flux, etc.)",
      "Balance technical specifications with artistic direction for optimal results"
    ],
    "welcome": "Hi! I'm Image Prompt Engineer. Translates visual concepts into precise prompts that produce stunning AI photography.",
    "featured": true,
    "color": "amber"
  },
  {
    "id": "engineering-backend-architect",
    "slug": "engineering-backend-architect",
    "icon": "🏗️",
    "name": "Backend Architect",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4.1,
    "sales": 671,
    "description": "Senior backend architect specializing in scalable system design, database architecture, API development, and cloud infrastructure. Builds robust, secure, performant server-side applications and microservices",
    "longDescription": "Designs the systems that hold everything up — databases, APIs, cloud, scale.",
    "features": [
      "Senior backend architect specializing in scalable system design, database architecture, API development, and cloud infrastructure. Builds robust, secure, performant server-side applications and microservices"
    ],
    "prompts": [
      "Tell Backend Architect what you are working on"
    ],
    "welcome": "Hi! I'm Backend Architect. Designs the systems that hold everything up — databases, APIs, cloud, scale.",
    "featured": true,
    "color": "blue"
  },
  {
    "id": "engineering-data-visualization-engineer",
    "slug": "engineering-data-visualization-engineer",
    "icon": "📈",
    "name": "Data Visualization Engineer",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4,
    "sales": 240,
    "description": "Expert data visualization engineer — chart-type selection by data and question, perceptually honest encodings, colorblind-safe data palettes, accessible and interactive charts, and rendering large datasets performantly with D3, Vega, and charting libraries.",
    "longDescription": "The chart's job is to tell the truth fast. Pick the encoding the eye reads accurately, and never let a pretty axis lie.",
    "features": [
      "Expert data visualization engineer — chart-type selection by data and question, perceptually honest encodings, colorblind-safe data palettes, accessible and interactive charts, and rendering large datasets performantly with D3, Vega, and charting libraries."
    ],
    "prompts": [
      "Tell Data Visualization Engineer what you are working on"
    ],
    "welcome": "Hi! I'm Data Visualization Engineer. The chart's job is to tell the truth fast. Pick the encoding the eye reads accurately, and never let a pretty axis lie.",
    "featured": true,
    "color": "#0F766E"
  },
  {
    "id": "engineering-git-workflow-master",
    "slug": "engineering-git-workflow-master",
    "icon": "🌿",
    "name": "Git Workflow Master",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4,
    "sales": 590,
    "description": "Expert in Git workflows, branching strategies, and version control best practices including conventional commits, rebasing, worktrees, and CI-friendly branch management.",
    "longDescription": "Clean history, atomic commits, and branches that tell a story.",
    "features": [
      "Expert in Git workflows, branching strategies, and version control best practices including conventional commits, rebasing, worktrees, and CI-friendly branch management."
    ],
    "prompts": [
      "Tell Git Workflow Master what you are working on"
    ],
    "welcome": "Hi! I'm Git Workflow Master. Clean history, atomic commits, and branches that tell a story.",
    "featured": true,
    "color": "orange"
  },
  {
    "id": "engineering-knowledge-graph-engineer",
    "slug": "engineering-knowledge-graph-engineer",
    "icon": "🧠",
    "name": "Knowledge Graph Engineer",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4.2,
    "sales": 1622,
    "description": "Structures information and capabilities into interconnected nodes (entities) and edges (relationships) — enabling dynamic context navigation, modular competency chaining, lower token costs, and hallucination reduction.",
    "longDescription": "Flat files are dead. Every piece of information is a node; every relationship is an edge. Navigate the graph, not the noise.",
    "features": [
      "Structures information and capabilities into interconnected nodes (entities) and edges (relationships) — enabling dynamic context navigation, modular competency chaining, lower token costs, and hallucination reduction."
    ],
    "prompts": [
      "Tell Knowledge Graph Engineer what you are working on"
    ],
    "welcome": "Hi! I'm Knowledge Graph Engineer. Flat files are dead. Every piece of information is a node; every relationship is an edge. Navigate the graph, not the noise.",
    "featured": true,
    "color": "violet"
  },
  {
    "id": "engineering-payments-billing-engineer",
    "slug": "engineering-payments-billing-engineer",
    "icon": "💳",
    "name": "Payments & Billing Engineer",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4.4,
    "sales": 404,
    "description": "Expert payments engineer for PSP integrations (Stripe, Adyen, Braintree, PayPal), idempotent payment flows, webhook processing, subscription billing, SCA/3DS, PCI scope reduction, and financial reconciliation.",
    "longDescription": "Money moves exactly once, or not at all. Idempotency first, webhooks as truth, reconciliation always.",
    "features": [
      "Design payment flows where every money mutation is idempotent, auditable, and driven to a terminal state",
      "Build webhook consumers that verify signatures, deduplicate events, and tolerate out-of-order and repeated delivery",
      "Reconcile internal ledgers against processor payouts so every cent is accounted for, every day"
    ],
    "prompts": [
      "Tell Payments & Billing Engineer what you are working on"
    ],
    "welcome": "Hi! I'm Payments & Billing Engineer. Money moves exactly once, or not at all. Idempotency first, webhooks as truth, reconciliation always.",
    "featured": true,
    "color": "#2E7D32"
  },
  {
    "id": "engineering-platform-engineer",
    "slug": "engineering-platform-engineer",
    "icon": "🛤️",
    "name": "Platform Engineer",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4,
    "sales": 530,
    "description": "Expert internal developer platform (IDP) engineer specializing in golden paths, paved roads, and self-serve infrastructure that multiplies engineering velocity.",
    "longDescription": "The platform is the product. If developers can't self-serve it, you haven't finished building it.",
    "features": [
      "A platform feature nobody uses is worse than no feature — it adds maintenance burden without value",
      "Track adoption (% of teams using each paved road) before declaring a feature \"shipped\"",
      "If adoption < 30% after 90 days, kill or rebuild the feature"
    ],
    "prompts": [
      "Ask Platform Engineer about a platform feature nobody uses is worse than no feature"
    ],
    "welcome": "Hi! I'm Platform Engineer. The platform is the product. If developers can't self-serve it, you haven't finished building it.",
    "featured": true,
    "color": "#0EA5E9"
  },
  {
    "id": "engineering-realtime-collaboration-engineer",
    "slug": "engineering-realtime-collaboration-engineer",
    "icon": "🤝",
    "name": "Realtime Collaboration Engineer",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4,
    "sales": 940,
    "description": "Expert realtime systems engineer for WebSocket/SSE infrastructure, presence, CRDT and OT-based collaborative editing, offline-first sync engines, and fan-out scaling with reconnect-safe protocols.",
    "longDescription": "Every keystroke is a distributed system. Converge, don't collide — and assume the network just dropped.",
    "features": [
      "Expert realtime systems engineer for WebSocket/SSE infrastructure, presence, CRDT and OT-based collaborative editing, offline-first sync engines, and fan-out scaling with reconnect-safe protocols."
    ],
    "prompts": [
      "Tell Realtime Collaboration Engineer what you are working on"
    ],
    "welcome": "Hi! I'm Realtime Collaboration Engineer. Every keystroke is a distributed system. Converge, don't collide — and assume the network just dropped.",
    "featured": true,
    "color": "#E11D48"
  },
  {
    "id": "engineering-section-508-specialist",
    "slug": "engineering-section-508-specialist",
    "icon": "♿",
    "name": "Section 508 Accessibility Specialist",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4.2,
    "sales": 362,
    "description": "Expert U.S. federal Section 508 accessibility engineer (the 508 legal baseline is WCAG 2.0 Level AA; WCAG 2.1/2.2 AA are recommended best practice, and ADA Title II requires WCAG 2.1 AA for state/local government) specializing in accessible web development, ARIA implementation, screen reader testing (JAWS/NVDA/VoiceOver), keyboard navigation, color contrast, accessible forms and PDFs, VPAT/ACR authoring, automated and manual auditing (axe/WAVE/Lighthouse), and remediation for government and enterprise sites",
    "longDescription": "A meticulous accessibility engineer who makes sure every user — regardless of ability — can perceive, navigate, understand, and operate a site, holding the line on the Section 508 legal baseline of WCAG 2.0 Level AA while targeting WCAG 2.1/2.2 AA as best practice (and WCAG 2.1 AA where ADA Title II applies to state and local government), testing with real assistive technology instead of trusting a green automated score, because the 30% of barriers a scanner can't catch are exactly the ones that lock a screen reader user out of a government service they have a legal right to use.",
    "features": [
      "Keyboard Operability: full keyboard access, visible focus, logical order, no traps, and skip mechanisms",
      "Assistive-Technology Testing: JAWS, NVDA, VoiceOver, TalkBack, Dragon, and screen-magnification",
      "Perceivability: color contrast, text resize/reflow, non-text alternatives, captions, and audio description",
      "Accessible Forms: labels, instructions, programmatic error association, and announced validation",
      "Document Accessibility: tagged PDFs, reading order, alt text, and accessible Office documents",
      "Auditing & Reporting: automated scans, manual evaluation, and VPAT/ACR (Accessibility Conformance Report) authoring"
    ],
    "prompts": [
      "Ask Section 508 Accessibility Specialist about keyboard Operability"
    ],
    "welcome": "Hi! I'm Section 508 Accessibility Specialist. A meticulous accessibility engineer who makes sure every user — regardless of ability — can perceive, navigate, understand, and operate a site, holding the line on the Section 508 legal baseline of WCAG 2.0 Level AA while targeting WCAG 2.1/2.2 AA as best practice (and WCAG 2.1 AA where ADA Title II applies to state and local government), testing with real assistive technology instead of trusting a green automated score, because the 30% of barriers a scanner can't catch are exactly the ones that lock a screen reader user out of a government service they have a legal right to use.",
    "featured": true,
    "color": "blue"
  },
  {
    "id": "engineering-senior-developer",
    "slug": "engineering-senior-developer",
    "icon": "💎",
    "name": "Senior Developer",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4.2,
    "sales": 1712,
    "description": "Premium implementation specialist - Masters Laravel/Livewire/FluxUI, advanced CSS, Three.js integration",
    "longDescription": "Premium full-stack craftsperson — Laravel, Livewire, Three.js, advanced CSS.",
    "features": [
      "Premium implementation specialist - Masters Laravel/Livewire/FluxUI, advanced CSS, Three.js integration"
    ],
    "prompts": [
      "Read task list from PM agent",
      "Understand specification requirements (don't add features not requested)",
      "Plan premium enhancement opportunities",
      "Identify Three.js or advanced technology integration points"
    ],
    "welcome": "Hi! I'm Senior Developer. Premium full-stack craftsperson — Laravel, Livewire, Three.js, advanced CSS.",
    "featured": true,
    "color": "green"
  },
  {
    "id": "engineering-solidity-smart-contract-engineer",
    "slug": "engineering-solidity-smart-contract-engineer",
    "icon": "⛓️",
    "name": "Solidity Smart Contract Engineer",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4.5,
    "sales": 1375,
    "description": "Expert Solidity developer specializing in EVM smart contract architecture, gas optimization, upgradeable proxy patterns, DeFi protocol development, and security-first contract design across Ethereum and L2 chains.",
    "longDescription": "Battle-hardened Solidity developer who lives and breathes the EVM.",
    "features": [
      "Expert Solidity developer specializing in EVM smart contract architecture, gas optimization, upgradeable proxy patterns, DeFi protocol development, and security-first contract design across Ethereum and L2 chains."
    ],
    "prompts": [
      "Tell Solidity Smart Contract Engineer what you are working on"
    ],
    "welcome": "Hi! I'm Solidity Smart Contract Engineer. Battle-hardened Solidity developer who lives and breathes the EVM.",
    "featured": true,
    "color": "orange"
  },
  {
    "id": "engineering-universal-document-compiler",
    "slug": "engineering-universal-document-compiler",
    "icon": "📑",
    "name": "Universal Document Compiler",
    "category": "مهندسی",
    "division": "engineering",
    "divisionLabel": "Engineering",
    "price": 49000,
    "rating": 4,
    "sales": 1700,
    "description": "Architect of schema-agnostic document ASTs, algorithmic data-shape layout inference, bidirectional CST-to-canvas synchronization, and universal paged document publishing.",
    "longDescription": "The shape of the data dictates the architecture of the page; no human thought should ever be constrained by static schemas.",
    "features": [
      "Executive CV / Resume (ATS-optimized keyword hierarchies).",
      "Technical Specification / Architecture Blueprint (System diagrams, tables, benchmarks).",
      "Commercial Proposal & Scope of Work (Deliverables, milestone timelines, financial schedules).",
      "Clinical / Diagnostic Report (Patient metrics, laboratory tables, observations)."
    ],
    "prompts": [
      "Ask Universal Document Compiler about executive CV / Resume (ATS-optimized keyword hierarchies)"
    ],
    "welcome": "Hi! I'm Universal Document Compiler. The shape of the data dictates the architecture of the page; no human thought should ever be constrained by static schemas.",
    "featured": true,
    "color": "#3B82F6"
  }
];
